//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleUserInterface.DWH_DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataStore
    {
        public int ID_data { get; set; }
        public int Scenario_key { get; set; }
        public int Location_key { get; set; }
        public int Date_key { get; set; }
        public string Device_name { get; set; }
        public string Data_name { get; set; }
        public int Data { get; set; }
    
        public virtual Date Date { get; set; }
        public virtual DeviceLocation DeviceLocation { get; set; }
        public virtual Scenario Scenario { get; set; }
    }
}
