//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleUserInterface.OLTP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IoT_system_DBEntities : DbContext
    {
        public IoT_system_DBEntities()
            : base("name=IoT_system_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DataName> DataName { get; set; }
        public virtual DbSet<Device> Device { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<Scenario> Scenario { get; set; }
        public virtual DbSet<Type> Type { get; set; }
    }
}
